[package]
name = "gf256"
version = "0.1.0"
authors = ["Christopher Haster <chaster@utexas.edu>"]
edition = "2018"

[lib]
bench = false

[[bench]]
name = "xmul"
harness = false

[[bench]]
name = "gfmul"
harness = false

[[bench]]
name = "gfdiv"
harness = false

[[bench]]
name = "crc"
harness = false

[features]
# Enables features only found on a nightly compiler
#
# Most notably this is required to leverage pmull on aarch64, see this
# tracking issue:
# https://github.com/rust-lang/rust/issues/48556
#
nightly-features = []

[dev-dependencies]
criterion = {version="0.3", features=["html_reports"]}

[dependencies]
gf256-macros = {path="gf256-macros"}
cfg-if = "1.0.0"
