name: test
on: [push, pull_request]

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@nightly
    - name: test
      run: |
        make test

  test-docs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@nightly
    - name: test
      run: |
        make docs

  test-configs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@nightly
    - name: test
      run: |
        make test-configs

  test-bench:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@nightly
    - name: test
      run: |
        make bench

